name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run build
      - run: npm test

  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure package.json version is bumped in PR
        run: |
          git fetch origin main
          PREV_VERSION=$(git show origin/main:package.json | jq -r .version)
          NEW_VERSION=$(jq -r .version package.json)
          if [ "$PREV_VERSION" = "$NEW_VERSION" ]; then
            echo "❌ Version not updated. Please bump package.json version."
            exit 1
          else
            echo "✅ Version updated."
